class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'pea'
        self.UnzipMirrorCommand = 'peaunzip'
        self.TarMirrorCommand = 'peatar'
        self.ZipMirrorCommand = 'peazip'
        self.CancelMirror = 'peacancel'
        self.CancelAllCommand = 'peacancelall'
        self.ListCommand = 'pealist'
        self.StatusCommand = 'peastatus'
        self.AuthorizedUsersCommand = 'peausers'
        self.AuthorizeCommand = 'peaauthorize'
        self.UnAuthorizeCommand = 'peaunauthorize'
        self.AddSudoCommand = 'peaaddsudo'
        self.RmSudoCommand = 'pearmsudo'
        self.PingCommand = 'peaping'
        self.RestartCommand = 'pearestart'
        self.StatsCommand = 'peastats'
        self.HelpCommand = 'peahelp'
        self.LogCommand = 'pealog'
        self.SpeedCommand = 'peaspeedtest'
        self.CloneCommand = 'peaclone'
        self.CountCommand = 'peacount'
        self.WatchCommand = 'peawatch'
        self.TarWatchCommand = 'peatarwatch'
        self.DeleteCommand = 'peadel'
        self.ShellCommand = 'peashell'
        self.ExecHelpCommand = 'peaexechelp'

BotCommands = _BotCommands()
